name: Ollama
'on':
  push:
jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
    - name: Install ollama
      run: curl -fsSL https://ollama.com/install.sh | sh
    - name: Run ollama
      run: |
        # ollama serve &
        ollama pull llama3.2
    - name: Call ollama API
      run: |
        curl -d '{"model": "llama3.2", "stream": false, "prompt":"Whatever I say, answer with Yes"}' http://localhost:11434/api/generate